### PR TITLE
Portal redesign styling and static layout

### PR DESCRIPTION
**Pull request by redwire**
If you can't build the portal stuff with just the build script, try running

    npm install -g gulp

before re-running the build script, and let me know if you had to do so.

There are three routes right now that can be used to check out each page:

1. Index/home page: `/testportal`
2. Channels page: `/testchannels`
3. Articles page: `/testarticles`

Each one is on `localhost:3090` of course.

### CODE REVIEW

**Comment by redwire** [comment]
This PR now includes commits to cover #113.

**Comment by redwire** [comment]
This PR now includes commits to cover #114.

**Comment by redwire** [comment]
The channels page is all done and ready to go.

**Comment by redwire** [comment]
This now has everything I can hope it would have this sprint. Please merge when ready.

**Comment by misaakidis** [comment]
Even after installing gulp globally I'm getting this error:


.../ceno/ceno-client/gulpfile.js:3
let fs = require('fs');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)


As well as a lot of warnings:
Preparing CENO Portal.
*  Installing any missing dependencies.
npm WARN prefer global babel@6.1.18 should be installed with -g
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-types/node_modules/babel-traverse requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-computed-properties/node_modules/babel-helper-define-map/node_modules/babel-types requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-computed-properties/node_modules/babel-helper-define-map/node_modules/babel-types/node_modules/babel-traverse requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-computed-properties/node_modules/babel-template/node_modules/babel-types requires babel-traverse@'^6.2.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-computed-properties/node_modules/babel-template/node_modules/babel-types requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-unicode-regex/node_modules/babel-helper-regex/node_modules/babel-types requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-types requires babel-traverse@'^6.2.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-template requires babel-traverse@'^6.2.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/node_modules/babel-traverse requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-template/node_modules/babel-traverse requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/babel-core/node_modules/babel-generator requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/babel-core/node_modules/babel-template requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/babel-core/node_modules/babel-register requires lodash@'^3.10.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/gulp-babel/node_modules/babel-core/node_modules/babel-generator requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/gulp-babel/node_modules/babel-core/node_modules/babel-template requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/gulp-babel/node_modules/babel-core/node_modules/babel-register requires lodash@'^3.10.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/gulp-babel/node_modules/babel-core/node_modules/babel-traverse requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/prometheas/ceno-eq/ceno-client/node_modules/gulp-babel/node_modules/babel-core/node_modules/babel-types requires lodash@'^3.10.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined

**Comment by misaakidis** [comment]
When running client, on first request I get this:

```
Nov 11, 2015 16:59:19:913 CENO proxy server listening for HTTP requests at http://127.0.0.1:3090
2015/11/24 16:59:45 http: panic serving 127.0.0.1:42521: runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc8200cb1e0, 0x7f8139cbc9b0, 0xc82002a0f8)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x7f8139cbcc10, 0xc82011c0b0, 0x739c20, 0xc820107230, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:101 +0x34
main.CreatePortalPage(0x7f8137e8e058, 0xc82011c0b0, 0xc82008d0a0)
	/home/prometheas/ceno-eq/ceno-client/src/portal.go:87 +0xc87
net/http.HandlerFunc.ServeHTTP(0x902e70, 0x7f8137e8e058, 0xc82011c0b0, 0xc82008d0a0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820011770, 0x7f8137e8e058, 0xc82011c0b0, 0xc82008d0a0)
	/usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820018960, 0x7f8137e8e058, 0xc82011c0b0, 0xc82008d0a0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200cb1e0)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
2015/11/24 16:59:46 http: panic serving 127.0.0.1:42523: runtime error: invalid memory address or nil pointer dereference
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc82011c370, 0x7f8139cbc9b0, 0xc82011a028)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x7f8139cbcc10, 0xc8200cb340, 0x739c20, 0xc8201079e0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:101 +0x34
main.CreatePortalPage(0x7f8137e8e058, 0xc8200cb340, 0xc8201281c0)
	/home/prometheas/ceno-eq/ceno-client/src/portal.go:87 +0xc87
net/http.HandlerFunc.ServeHTTP(0x902e70, 0x7f8137e8e058, 0xc8200cb340, 0xc8201281c0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820011770, 0x7f8137e8e058, 0xc8200cb340, 0xc8201281c0)
	/usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820018960, 0x7f8137e8e058, 0xc8200cb340, 0xc8201281c0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82011c370)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
2015/11/24 16:59:51 http: panic serving 127.0.0.1:42527: runtime error: invalid memory address or nil pointer dereference
goroutine 28 [running]:
net/http.(*conn).serve.func1(0xc8200cb600, 0x7f8139cbc9b0, 0xc82002a208)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x7f8139cbcc10, 0xc82011c4d0, 0x739c20, 0xc82019e180, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:101 +0x34
main.CreatePortalPage(0x7f8137e8e058, 0xc82011c4d0, 0xc82008d260)
	/home/prometheas/ceno-eq/ceno-client/src/portal.go:87 +0xc87
net/http.HandlerFunc.ServeHTTP(0x902e70, 0x7f8137e8e058, 0xc82011c4d0, 0xc82008d260)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820011770, 0x7f8137e8e058, 0xc82011c4d0, 0xc82008d260)
	/usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820018960, 0x7f8137e8e058, 0xc82011c4d0, 0xc82008d260)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200cb600)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Pull request merged**
